import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { GiHamburgerMenu } from "react-icons/Gi";
import RSC from "../components/RscComponent";
import Meet from "../components/TeamSectionComponent.js";
import Advice from "@/components/AdviceComponent";
import Three from "../components/ThreeComponent";
import Firm from "../components/FirmComponent";
import Last from "../components/Last";
import Header from "@/components/HeaderComponent";
import FAQ from "@/components/FAQComponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.header2}>
        {/* <div className={styles.navbar}>
      <div className={styles.navbarheading}>
      <img src="https://capp.nicepage.com/1a3b34123e5a23fa2ec02642c3f27a25764372fe/images/default-logo.png" alt="log-img" />
       </div>
       <div className={styles.navbaricon}>
       <GiHamburgerMenu/>
      </div> 
      </div>

      <div className={styles.section1}>
      <div className={styles.section1place} id="section1place">
      <div className={styles.rectangle} id="rectangle">  
        <h1 className={styles.p1} id="p1">What We Believe</h1>
        <p className={styles.p2}>Nibh venenatis cras sed felis eget velit aliquet sagittis id. Tellus pellentesque eu tincidunt tortor aliquam nulla. </p>
        <p class={styles.p3}>Image from <a href="https://freepik.com/photos/backround" class={styles.a1}>Freepik</a>
            </p>
        <div className={styles.buttons12} >
        <a href="#">READ MORE</a>
        </div>
      </div>
    </div>
  </div> */}
        <Header />
        <RSC />
        <Meet />
        <Advice />
        <Three />
        <Firm />
        <Last />
        <div className={styles.FAQ}>
          <FAQ />
        </div>
      </main>
    </>
  );
}
