import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
// import RSC from "../components/RscComponent";
import TeamSection from "../components/homepage/teamSectionComponent.js";
import Advice from "@/components/homepage/adviceComponent";
import Three from "../components/homepage/threeComponent";
import Firm from "../components/FirmComponent";
import Last from "../components/homepage/last";
import Header from "@/components/homepage/headerComponent";
// import Botstrap from "@/components/homepage/rscComponent"
import RSC from "@/components/homepage/rscComponent"
import FAQ from "@/components/FAQComponent";
import Navbar1 from "@/components/homepage/navbarComponent";
import FAQ1 from "@/components/homepage/faqtest";
import Test from "@/components/homepage/firm1";
import Test1 from "@/components/homepage/testing";





const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.header2}>
        {/* <div className={styles.navbar}>
      <div className={styles.navbarheading}>
      <img src="https://capp.nicepage.com/1a3b34123e5a23fa2ec02642c3f27a25764372fe/images/default-logo.png" alt="log-img" />
       </div>
       <div className={styles.navbaricon}>
       <GiHamburgerMenu/>
      </div> 
      </div>

      <div className={styles.section1}>
      <div className={styles.section1place} id="section1place">
      <div className={styles.rectangle} id="rectangle">  
        <h1 className={styles.p1} id="p1">What We Believe</h1>
        <p className={styles.p2}>Nibh venenatis cras sed felis eget velit aliquet sagittis id. Tellus pellentesque eu tincidunt tortor aliquam nulla. </p>
        <p class={styles.p3}>Image from <a href="https://freepik.com/photos/backround" class={styles.a1}>Freepik</a>
            </p>
        <div className={styles.buttons12} >
        <a href="#">READ MORE</a>
        </div>
      </div>
    </div>
  </div> */}
        <Navbar1/>
        <Header />
        
        {/* <Botstrap/>  */}
        <RSC />
        <TeamSection />
        
        <Advice/>
        <Three />
        {/* <Firm /> */}
        <Test/>
        <Last />
        
        <div className={styles.FAQ}>
          {/* <FAQ /> */}
        <FAQ1 />
        <Test1/>
         
        </div>
      </main>
    </>
  );
}
